{% from "lib/environment.sls" import environment -%}
{% from "akita/map.jinja" import props with context %}
# this file is managed by salt local changes will be overwritten

source /usr/share/chruby/chruby.sh
source /usr/share/chruby/auto.sh
chruby {{ salt.pillar.get('akita:versions:ruby') }}

export NED_SERVICE={{ props.get('ned_service') }}
export NED_USERAPP=akita
export NED_PASSWORD={{ salt.pillar.get('secrets:akita:ned-password') }}

export CAS_URL={{ props.get('cas_url') }}

export MAILER_ADDRESS={{ props.get('mailer_address') }}
export MAILER_PORT={{ props.get('mailer_port') }}
export RAILS_ENV={{ props.get('rails_env') }}
export SECRET_KEY_BASE={{ salt.pillar.get('secrets:akita:rails-secret') }}

export EXACTTARGET_ID={{ salt.pillar.get('secrets:akita:exact-target-id') }}
export EXACTTARGET_SECRET={{ salt.pillar.get('secrets:akita:exact-target-secret') }}

export SALESFORCE_HOST={{ props.get('salesforce_host') }}
export SALESFORCE_CLIENT_ID={{ salt.pillar.get('secrets:akita:salesforce-client-id') }}
export SALESFORCE_CLIENT_SECRET={{ salt.pillar.get('secrets:akita:salesforce-client-secret') }}
export SALESFORCE_USERNAME={{ props.get('salesforce_user') }}
export SALESFORCE_PASSWORD={{ salt.pillar.get('secrets:akita:salesforce-password') }}
export SALESFORCE_CONSUMER_APP=salesforce
export SALESFORCE_CONSUMER_PASSWORD={{ salt.pillar.get('secrets:akita:salesforce-consumer-password') }}
export SALESFORCE_IMPORT_NOTIFY_TO=edboardmgmt@plos.org

export JWT_SHARED_SECRET={{ salt.pillar.get('secrets:nedcas:jwt-shared-secret') }}

export MOODLE_TOKEN={{ salt.pillar.get('secrets:akita:moodle-token') }}
